// Code generated by "stringer -type Op"; DO NOT EDIT.

package crun

import "strconv"

const _Op_name = "OpLiteralOpRepeatOpAlternate"

var _Op_index = [...]uint8{0, 9, 17, 28}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
